# coding: utf-8

"""
    Peptide Match OpenAPI 2.0

    This is PeptideMatch OpenAPI.

    OpenAPI spec version: 2.0.0
    Contact: chenc@udel.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.protein_match_range import ProteinMatchRange


class TestProteinMatchRange(unittest.TestCase):
    """ ProteinMatchRange unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProteinMatchRange(self):
        """
        Test ProteinMatchRange
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.protein_match_range.ProteinMatchRange()
        pass


if __name__ == '__main__':
    unittest.main()
