# coding: utf-8

"""
    Peptide Match OpenAPI 2.0

    This is PeptideMatch OpenAPI.

    OpenAPI spec version: 2.0.0
    Contact: chenc@udel.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.peptide_match_api20_api import PeptideMatchAPI20Api


class TestPeptideMatchAPI20Api(unittest.TestCase):
    """ PeptideMatchAPI20Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.peptide_match_api20_api.PeptideMatchAPI20Api()

    def tearDown(self):
        pass

    def test_match_get_get(self):
        """
        Test case for match_get_get

        Do peptide match using GET method.
        """
        pass

    def test_match_post_post(self):
        """
        Test case for match_post_post

        Do peptide match using POST method.
        """
        pass


if __name__ == '__main__':
    unittest.main()
