# coding: utf-8

"""
    Peptide Match OpenAPI 2.0

    This is PeptideMatch OpenAPI.

    OpenAPI spec version: 2.0.0
    Contact: chenc@udel.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ProteinMatchingPeptide(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'peptide': 'str',
        'match_range': 'list[ProteinMatchRange]'
    }

    attribute_map = {
        'peptide': 'peptide',
        'match_range': 'matchRange'
    }

    def __init__(self, peptide=None, match_range=None):
        """
        ProteinMatchingPeptide - a model defined in Swagger
        """

        self._peptide = None
        self._match_range = None

        if peptide is not None:
          self.peptide = peptide
        if match_range is not None:
          self.match_range = match_range

    @property
    def peptide(self):
        """
        Gets the peptide of this ProteinMatchingPeptide.
        Query peptide.

        :return: The peptide of this ProteinMatchingPeptide.
        :rtype: str
        """
        return self._peptide

    @peptide.setter
    def peptide(self, peptide):
        """
        Sets the peptide of this ProteinMatchingPeptide.
        Query peptide.

        :param peptide: The peptide of this ProteinMatchingPeptide.
        :type: str
        """

        self._peptide = peptide

    @property
    def match_range(self):
        """
        Gets the match_range of this ProteinMatchingPeptide.

        :return: The match_range of this ProteinMatchingPeptide.
        :rtype: list[ProteinMatchRange]
        """
        return self._match_range

    @match_range.setter
    def match_range(self, match_range):
        """
        Sets the match_range of this ProteinMatchingPeptide.

        :param match_range: The match_range of this ProteinMatchingPeptide.
        :type: list[ProteinMatchRange]
        """

        self._match_range = match_range

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ProteinMatchingPeptide):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
