# coding: utf-8

"""
    Peptide Match OpenAPI 2.0

    This is PeptideMatch OpenAPI.

    OpenAPI spec version: 2.0.0
    Contact: chenc@udel.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ProteinMatchRange(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start': 'int',
        'end': 'int',
        'replaced_locs': 'list[int]'
    }

    attribute_map = {
        'start': 'start',
        'end': 'end',
        'replaced_locs': 'replacedLocs'
    }

    def __init__(self, start=None, end=None, replaced_locs=None):
        """
        ProteinMatchRange - a model defined in Swagger
        """

        self._start = None
        self._end = None
        self._replaced_locs = None

        if start is not None:
          self.start = start
        if end is not None:
          self.end = end
        if replaced_locs is not None:
          self.replaced_locs = replaced_locs

    @property
    def start(self):
        """
        Gets the start of this ProteinMatchRange.

        :return: The start of this ProteinMatchRange.
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """
        Sets the start of this ProteinMatchRange.

        :param start: The start of this ProteinMatchRange.
        :type: int
        """

        self._start = start

    @property
    def end(self):
        """
        Gets the end of this ProteinMatchRange.

        :return: The end of this ProteinMatchRange.
        :rtype: int
        """
        return self._end

    @end.setter
    def end(self, end):
        """
        Sets the end of this ProteinMatchRange.

        :param end: The end of this ProteinMatchRange.
        :type: int
        """

        self._end = end

    @property
    def replaced_locs(self):
        """
        Gets the replaced_locs of this ProteinMatchRange.

        :return: The replaced_locs of this ProteinMatchRange.
        :rtype: list[int]
        """
        return self._replaced_locs

    @replaced_locs.setter
    def replaced_locs(self, replaced_locs):
        """
        Sets the replaced_locs of this ProteinMatchRange.

        :param replaced_locs: The replaced_locs of this ProteinMatchRange.
        :type: list[int]
        """

        self._replaced_locs = replaced_locs

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ProteinMatchRange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
